

def should_copy from, to
  !File.exists?(to) || File.read(to) != File.read(from)
end

def copy_changed_files from, to
  files = FileList["#{from}/**/*"].
    reject { |f| File.directory?(f) }.
    map { |f| f.gsub(from, '') }

  files.each do |file|
    from_file = "#{from}#{file}"
    to_file = "#{to}#{file}"
    if should_copy(from_file, to_file)
      puts ">> Copied: #{from_file} to: #{to_file}"
      FileUtils.mkdir_p File.dirname(to_file)
      FileUtils.cp from_file, to_file
    end
  end

  puts "[WARNING]: No files were deleted from the destination - you may need to manually DELETE desired files"
end

desc "Build the files and place them where they belong"
task :deploy do
  `jekyll --no-server --no-auto`
  copy_changed_files '_site', '..'
end

