sprout 'sprout-flashplayer-bundle'
require 'sprout/tasks/flashplayer_task'
require 'sprout/tasks/fdb_task'
require 'sprout/tasks/mxmlc_task'
require 'sprout/tasks/compc_task'
require 'sprout/tasks/asdoc_task'
require 'sprout/tasks/adl_task'
require 'sprout/tasks/adt_task'
require 'sprout/tasks/fdb_task'

require 'sprout/tasks/mxmlc_helper'
require 'sprout/tasks/mxmlc_flex_builder'
require 'sprout/tasks/mxmlc_unit'
require 'sprout/tasks/mxmlc_debug'
require 'sprout/tasks/mxmlc_deploy'
require 'sprout/tasks/mxmlc_document'
require 'sprout/tasks/mxmlc_stylesheet'
require 'sprout/tasks/mxmlc_swc'

require 'sprout/tasks/fcsh'
