#!/usr/bin/env ruby

require 'rubygems'
require 'sprout'
require 'generators/<%= input.snake_case %>_generator'

generator = <%= input.snake_case %>Generator.new
generator.parse! ARGV
generator.execute