=begin
Copyright (c) 2007 Pattern Park

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
=end
require 'erb'

module Sprout

  class SimpleResolver #:nodoc:

    def initialize(template, output, files, base_dir=nil)
      @template = template
      @output = output
      @files = files
      @base_dir = base_dir
      @ignored_files = []
      execute
      finish
    end
  
    def execute
      template_file = File.open(@template, 'r')
      content = template_file.read
      result = ERB.new(content, nil, '>').result(binding)

      output_file = File.open(@output, 'w')
      output_file.write(result)
    
      template_file.close
      output_file.close
    end
  
    def files
      return @files
    end

    def finish
      if(@ignored_files.size > 0)
        Logger.puts '>> SimpleResolver ignored the following files because their names were invalid:'
        @ignored_files.each do |file|
          puts file
        end
      end
    end
  
    def xml_edit_warning
      return <<EOF
    <!--
    DO NOT EDIT THIS FILE!
    This file was auto-generated from
    an ERB template which can be
    found at: 
    #{@template}
    -->
EOF
    end
  
    def edit_warning
      return <<EOF
  /*************************************
   * DO NOT EDIT THIS FILE!
   * This file was auto-generated from
   * an ERB template which can be
   * found at: 
   * #{@template}
   *************************************/
EOF
    end
  end
end