- !ruby/object:Sprout::RemoteFileTarget 
  platform: macosx
  url: http://projectsprouts.googlecode.com/files/air-sdk-osx-1.0.0.zip
  md5: 4c29b13f191d640abb2f64272d6f771d
- !ruby/object:Sprout::RemoteFileTarget 
  platform: win32
  url: http://airdownload.adobe.com/air/win/download/1.0/AdobeAIRSDK.zip
- !ruby/object:Sprout::RemoteFileTarget 
  platform: linux
  archive_path: adt
