- !ruby/object:Sprout::RemoteFileTarget 
  platform: macosx
  url: http://projectsprouts.googlecode.com/files/swfmill-0.2.12-macosx.tar.gz
  archive_path: swfmill-0.2.12-macosx/swfmill
  md5: 9c708c0fc4977f774a70671e06420e52
- !ruby/object:Sprout::RemoteFileTarget 
  platform: win32
  url: http://www.swfmill.org/releases/swfmill-0.2.12-win32.zip
  archive_path: swfmill-0.2.12-win32/swfmill.exe
- !ruby/object:Sprout::RemoteFileTarget 
  platform: linux
  archive_path: swfmill
